language: java
jdk:
  - openjdk8

branches:
  only:
    - master #마스터 브랜치로 푸쉬될 떄만 자동 빌드 설정

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

notifications:
  email:
    recipients:
      imjee02@gmail.com
